# Generated by Django 2.1.1 on 2018-10-25 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_storage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recordings',
            new_name='Recording',
        ),
        migrations.AlterModelTable(
            name='recording',
            table='Recording',
        ),
    ]
