# Generated by Django 2.1.1 on 2018-10-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_storage', '0002_auto_20181025_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='path',
            field=models.CharField(max_length=255),
        ),
    ]
